### PR TITLE
Feature/4443 cycle time injection view add edit delete

### PR DESCRIPTION
**Pull request by jordanfontainecvp**
Feature/4443 cycle time injection view add edit delete

### CODE REVIEW

**Comment by jordanfontainecvp** [comment]
Adding Unit tests

**Review by billmiller13 — APPROVED** [review]
Looks good

**Review by billmiller13 — APPROVED** [review]
Did you mean to delete that last case in src/utils/selectors/QACert/assert.js  ?  

Also, take out that large commented block in src/utils/selectors/QACert/assert.js and just keep a local copy of it if you plan to re-introduce.  SonarQube will flag this as a code smell otherwise.

**Comment by jordanfontainecvp** [comment]
> Did you mean to delete that last case in src/utils/selectors/QACert/assert.js ?
> 
> Also, take out that large commented block in src/utils/selectors/QACert/assert.js and just keep a local copy of it if you plan to re-introduce. SonarQube will flag this as a code smell otherwise.

I didn't mean to, thanks for spotting that

**Review by billmiller13 — APPROVED** [review]
looks good

**Pull request merged**
