### PR TITLE
5348: refactor unit-tests

### PR DESCRIPTION
**Pull request by jeffreyaggrey**

### CODE REVIEW

**Review by Qb10 — DISMISSED** [review]

**Comment by subrataroyCVP** [comment]
image

**Comment by subrataroyCVP** [comment]
image

**Comment by subrataroyCVP** [comment]
@Qb10 are they passing for you?

**Comment by subrataroyCVP** [comment]
@JanellC 

This Pull Request is hanging around for a while.

**Review by subrataroyCVP — CHANGES_REQUESTED** [review]
These files are failing.
`src/additional-functions/useGetCheckedOutLocations.test.js`
`src/components/AboutHome/AboutHome.test.js`
`src/components/Accessories/Accessories.test.js`

Review the screenshots for errors.

image

image


image

**Pull request closed without merging**
