### PR TITLE
Failing Unit Tests - MP/UI

### PR DESCRIPTION
**Pull request by jordanfontainecvp**
LinearityInjection.test.js

CustomAccordion.test.js

DataTableRectangularDucts.test.js

create-modal-input-controls.test.js

src/components/DynamicTabs/DynamicTabs.test.js

src/components/QACertTestSummaryHeaderInfo/QACertTestSummaryHeaderInfo.test.js

### CODE REVIEW

**Comment by jordanfontainecvp** [comment]
still in progress

**Comment by jordanfontainecvp** [comment]
Screenshot (36)

**Comment by jordanfontainecvp** [comment]
Screenshot (37)

**Review by subrataroyCVP — CHANGES_REQUESTED** [review]
Unit Tests not addressed `src/store/actions/monitoringPlans.test.js`

image

As mentioned in the ticket.

image

**Comment by jordanfontainecvp** [comment]
Screenshot (39)

**Review by subrataroyCVP — APPROVED** [review]
LGTM. 

All the failing tests were addressed for the mentioned files.

**Review by RobertB-CVP — APPROVED** [review]
Try to improve sonarcloud coverage but past that it looks good

**Pull request merged**
